sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: 
    access-key-id:
    access-key-secret:  
    bucket-name: 
  redis:
    host: localhost
    port: 6379
    database: 1
  wechat:
    appid: wxe8cb4389a3a2cfa0
    secret: d9294c411869a2853c20041bdb9745ad
